version: "3"
services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      DB_USER: example
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 5432
  db:
    image: postgres
    ports:
      - "8001:5432"
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
