version: "3"
services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
  db:
    image: postgres
    ports:
      - "8001:5432"
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
